NASA-IMPACT/veda-backend

- .github/workflows/develop.yml
- .github/workflows/main.yml
- .github/workflows/pr.yml
Upgrades deprecated Github Actions - #135
> Update actions/checkout and actions/setup-python

- raster_api/runtime/handler.py
Fix for #142 - leaving as a draft until we test, but this should be an easy fix
> Fix mangum db connection pool

- raster_api/runtime/handler.py
> Merge DB pooling change to main

- database/runtime/handler.py
- stac_api/runtime/src/api.py
- stac_api/runtime/src/app.py
- stac_api/runtime/src/core.py
- stac_api/runtime/src/search.py
This PR adds the ability to search through collections with temporal and spatial boundaries as is available for items.
A new function, `pgstac.collection_id_search` has been added to the DB and new endpoints have been wired up in stac-fastapi at `/collection-id-search`. This endpoint takes intersection, bbox, and datetime queries just as the item search does and appropriate models have been added to ensure correctness of generated documentation. 
Closes #131
> Collection search

- README.md
The old veda-documentation repo has been archived
> Point README to veda-docs

- database/infrastructure/config.py
- database/infrastructure/construct.py
Implements #177 
Deployed (but not tested as described in the linked issue) under veda-backend-isayah - https://isayah-stac.delta-backend.com/
> RDS Proxy initial implementation

- raster_api/runtime/setup.py
Pulled out of #197 - addresses #198
> Pin pydantic for now

- .github/workflows/pr.yml
Run cdk diff on specific stage based on the target branch in pre deployment action.
> ci: branch specific pre-deploy check on pull request action

- raster_api/runtime/setup.py
Temporary rollback rio-tiler to an earlier version
> fix(raster): temp downgrade rio tiler version

- app.py
- config.py
- domain/infrastructure/construct.py
Include app context config for bootstrap qualifier.
> feat: include app context config for bootstrap qualifier

- .github/workflows/develop.yml
- .github/workflows/pr.yml
- ingest_api/runtime/tests/conftest.py
Fixes failing dev test actions
> fix(ingest): try to fix dev actions

- ingest_api/runtime/src/auth.py
- ingest_api/runtime/src/schemas.py
Proposed fix for #265
I don't have a ton of visibility into potential MCP-specific auth issues, but this should resolve the reported 500 errors
- removes secret hash as a required auth parameter
- remove cog_default validator
> fix(ingest): fix MCP 500 errors

- raster_api/runtime/setup.py
- Add updates from PR #246 and unpin rio-tiler temporary post release version
- Pin starlette from PR #268 
- Unpin post release rio-tiler version #259
> fix(raster): incorporate updates from #246, #268, and unpin rio-tiler version

- .github/actions/cdk-deploy/action.yml
- app.py
- ingest_api/infrastructure/construct.py
- Updates externally triggered deployment action to pick up auth credentials for ingestion system
> feat(ci): ingest deploy action

- ingest_api/runtime/src/auth.py
The ingest/token endpoint is timing out--this change should reveal the exception for debugging
> fix(ingest): return failed login exception for debugging

- ingest_api/runtime/src/main.py
Another attempt to expose the cause of the token endpoint timeout
> fix(ingest): try #2 to return failed login exception for debugging

- raster_api/runtime/setup.py
see https://github.com/stac-utils/titiler-pgstac/pull/154
> fix(raster): update titiler-pgstac dependency for better statistics

- ingest_api/runtime/src/collection_publisher.py
https://github.com/NASA-IMPACT/veda-architecture/issues/384
> fix(ingest): fix invalid null stac properties

- ingest_api/infrastructure/construct.py
- routes/infrastructure/construct.py
- stac_api/runtime/src/core.py
Pull hotfix from main in #303 
```
git cherry-pick 7111e48
```
> chore: hotfix from main change search base condition

- database/infrastructure/construct.py
- raster_api/runtime/handler.py
- raster_api/runtime/setup.py
- raster_api/runtime/src/app.py
https://github.com/NASA-IMPACT/veda-backend/issues/315#issuecomment-1957843514
> fix: upgrade titiler.pgstac to 0.8.3

- .github/actions/cdk-deploy/action.yml
- .github/workflows/pr.yml
- database/infrastructure/construct.py
- network/infrastructure/construct.py
- raster_api/infrastructure/construct.py
- stac_api/infrastructure/construct.py
https://github.com/NASA-IMPACT/veda-deploy/issues/25
- Updates needed to deploy using `veda-deploy`
- Update version of GitHub actions
- for `veda-deploy` to be able to pass env vars from one stack to another
- Ran deployment using `veda-deploy` until successful
> fix(ci): updates for veda deploy

- .github/workflows/pr.yml
updates more github action versions
> ci: update predeploy actions

- ingest_api/runtime/src/main.py
- ingest_api/runtime/src/vedaloader.py
Change Ingestion `created_by` param to use `get_username` auth function
> fix: change get username function

- .github/workflows/cicd.yml
- .github/workflows/release.yml
- Fix: correct the name of the target branch for the develop deployment cicd
- Fix: return the release workflow trigger for pushes to develop and main branches
> ci: fix cicd target branch name and fix release workflow

- ingest_api/runtime/src/schemas.py
Pydantic v2 changes URL type behaviour, preventing JSON serialization (which we use to load collections into our catalog). We removed most instances of these types when we migrated to v2, but the stac-pydantic `Catalog` model (used in the `Collection` model) still uses `AnyUrl` for `stac_extensions`.
I'm not convinced this is necessarily a bug, but it is blocking our ingests, so I'm including a fix here rather than upstream (for now). There are changes to URLs on the pydantic v3 roadmap, which may or may not fix this.
Ref:
https://github.com/pydantic/pydantic/discussions/8211
https://github.com/pydantic/pydantic/issues/7186
> fix: Change stac_extension URL serialization

- ingest_api/infrastructure/construct.py
Add client id, config url to ingest construct.
> fix: add client id, config url to ingest construct

- database/runtime/handler.py
- stac_api/runtime/setup.py
- stac_api/runtime/src/app.py
- stac_api/runtime/src/config.py
- removed context extension from pgstac https://github.com/stac-utils/pgstac/blob/main/CHANGELOG.md#v090
- along with this release, the pgstac database should be upgraded to v0.9.6
- upgrade stac-fastapi to ~=5.0
- N/A
> feat(release)!: upgrade stac-fastapi 

- app.py
- docker-compose.yml
- ingest_api/infrastructure/config.py
- ingest_api/infrastructure/construct.py
- ingest_api/runtime/src/config.py
- ingest_api/runtime/src/main.py
- ingest_api/runtime/src/monitoring.py
- raster_api/infrastructure/config.py
- raster_api/infrastructure/construct.py
- raster_api/runtime/src/app.py
- raster_api/runtime/src/config.py
- raster_api/runtime/src/monitoring.py
- stac_api/infrastructure/config.py
- stac_api/infrastructure/construct.py
- stac_api/runtime/src/app.py
- stac_api/runtime/src/config.py
- stac_api/runtime/src/extension.py
- stac_api/runtime/src/monitoring.py
https://github.com/NASA-IMPACT/veda-architecture/issues/655
- Switch to using a middleware for logging, metrics, and traces (which are still limited until we get newer versions of titiler deployed)
- Adjust metrics to have more meaningful dimensions
- Consistency with other services
- Improved metrics to support meaningful alarms and dashboards
- Currently deployed to SIT
- New metrics currently available on SIT and dev monitoring stacks - see WIP dashboard on https://monitoring.dev.openveda.cloud/
> feat: switch to improved monitoring middleware
