raster_api/runtime/src/app.py
The `cog/validate` endpoint was failing with `Access Denied`. The `cog_info` function was missing the AWS session env.
=> Cog validate endpoint fix 

README.md
This PR is used to trigger a github actions dev deployment to upgrade pgstac to version 0.7.6. The `VEDA_DB_PGSTAC_VERSION` secret in `veda-backend-uah-dev-env` has been updated to `0.7.6`.
A snapshot `veda-backend-uah-dev-postgres-2023-05-17-pre-pgstac-upgrade` has been created for rds `veda-backend-uah-dev-postgres`
=> Pgstac upgrade to 0.7.6

setup.py
Pgstac 0.7.6 migration failed because of known bug https://github.com/stac-utils/pgstac/issues/180. Using version 0.7.4 which is the last stable release.
=> Upgrade to pgstac 0.7.4

database/runtime/handler.py
Change to the postgres search path to fix breaking change resulting from Pgstac >0.7
Note that VEDA_DB_SCHEMA_VERSION in secrets manager must be incremented before merge so custom handler resource will update when run in github actions.
=> Change db search path

stac_api/runtime/src/api.py
This PR removes the collection id search endpoint from the open api docs. We are still considering using aggregations instead and don't want to commit to supporting this search pattern long term (yet).
=> Do not advertise experimental endpoint

raster_api/infrastructure/construct.py
Export session credentials in raster api env setting fix [#194] needs to be put in the lambda function construct to be found at runtime
=> Put raster assume role config in lambda construct

README.md
- Updates a few outdated deployment requirements
- Adds links for node and jq installation
- Adds example virtual environment setup
- Markdown only
=> Minor updates to deployment docs

standalone_base_infrastructure/README.md, standalone_base_infrastructure/network_construct.py, standalone_base_infrastructure/standalone_config.py
https://github.com/NASA-IMPACT/veda-analytics/issues/86
=> Use NAT Gateway Service

raster_api/runtime/src/app.py
This PR enables the `/tileMatrixSets` endpoint so that options are provided should people choose a non-standard projection.
Closes #214
=> Enable TMS endpoints in TiTiler

raster_api/infrastructure/config.py, raster_api/infrastructure/construct.py, raster_api/runtime/src/app.py, raster_api/runtime/src/config.py, stac_api/infrastructure/config.py, stac_api/infrastructure/construct.py, stac_api/runtime/src/app.py, stac_api/runtime/src/config.py, stac_api/runtime/src/extension.py
Include path prefix for raster and stac APIs.
Related to Issue https://github.com/NASA-IMPACT/veda-backend/issues/208
NOTE: Before merging add the following to the secrets manager for backend `dev`:
```
VEDA_RASTER_PATH_PREFIX=/api/raster
VEDA_STAC_PATH_PREFIX=/api/stac
```
=> Include path prefix for raster and stac APIs

README.md
Improve instructions for destroying a veda-backend stack: add RDS subnet group manual removal step.
=> docs: improve instructions for destroying a veda-backend stack

app.py, permissions_boundary/infrastructure/construct.py
This PR pulls in the permissions boundary improvements from the GHG backend project.
=> fix: apply permissions boundary

app.py, raster_api/infrastructure/construct.py, routes/infrastructure/construct.py, stac_api/infrastructure/construct.py
The cloudfront distribution includes the `stage` env as the subdomain:
`{stage}.{domain_hosted_zone_name}.com`
=> fix: include stage subdomain in cloudfront distribution

raster_api/runtime/setup.py
Post release 6.2.3.post1 to get features/fixed which were added after 6.2.3 (fix for weighted spatial average)
=> fix(raster): pin rio-tiler 6.2.3.post1

app.py
A managed policy is needed for permission boundary
=> fix: use managed policy for permissions boundary

.github/workflows/develop.yml, .github/workflows/main.yml, .github/workflows/pr.yml
- Upgrade to github actions to resolve outdated node version warnings
- Add cdk deploy output to file to resolve set-output warning
- Conventional PR linter if not not updated: we may need to remove or replace if this [upgrade PR](https://github.com/CondeNast/conventional-pull-request-action/pull/19) is not accepted. For now, there is a warning in the pr action about forcing linter to run on an upgraded node version.
Parent issue https://github.com/NASA-IMPACT/veda-architecture/issues/345
=> fix(ci): upgrade github actions to resolve warnings

stac_api/infrastructure/construct.py
Include trailing slash in raster endpoint
=> fix: raster endpoint url fix for render links

ingest_api/infrastructure/config.py, ingest_api/runtime/src/config.py, ingest_api/runtime/src/schemas.py, ingest_api/runtime/src/validators.py
Minor fixes in ingest API to support cognito clients not configured with secrets. Tested end to end token generation, validation, and collection publication in externally deployed instance.
=> fix(ingest): use defaults for auth env configuration

stac_api/runtime/src/app.py, stac_api/runtime/src/config.py
This PR enables transactions for with automatic secret lookup. The goal here is not to expose this feature to end-users, so no further auth is involved.
Closes #269
=> feat: enable transactions extension for demo

.pre-commit-config.yaml, ingest_api/infrastructure/construct.py
- This PR updates the subnet type for the ingest api handler to use private subnets.
- This PR also updates the pre-commit yaml file
https://github.com/NASA-IMPACT/veda-backend/issues/280
- Update ingest api to use private subnets
- Update `pre-commit-config.yaml` to update `mypy` rev and add `additional_dependencies`
I manually update the dev ingest api lambda to have private subnets (previously, they were configured with public subnets) and tested the dev delta `/token` endpoint and the lambda endpoint itself.
=> fix: update ingest api subnet types and log format and update pre-commit config

raster_api/runtime/src/alternate_reader.py, raster_api/runtime/src/app.py
This PR adds support for alternate assets.
It is not as general as it could be, so there's a question here about what we aim to support. Non-s3 backends for these alt-assets are not currently supported. If we want that, we *could* add to the path arguments or else query params expected. Thoughts?
=> feat: alternate asset support in titiler

ingest_api/runtime/src/config.py
The stac ingestor config is missing the `stac_url` environment variable and is causing the collection validator to fail. This PR adds back the `stac_url` in settings.
```
{
"timestamp": "2024-02-12T15:34:51Z",
"level": "ERROR",
"message": "An error occurred running the application.",
"logger": "mangum.http",
"stackTrace": [
"  File \"/var/task/mangum/protocols/http.py\", line 58, in run\n    await app(self.scope, self.receive, self.send)\n",
"  File \"/var/task/fastapi/applications.py\", line 1054, in __call__\n    await super().__call__(scope, receive, send)\n",
"  File \"/var/task/starlette/applications.py\", line 123, in __call__\n    await self.middleware_stack(scope, receive, send)\n",
"  File \"/var/task/starlette/middleware/errors.py\", line 186, in __call__\n    raise exc\n",
" …
```
=> fix: include stac url in ingestor config

ingest_api/runtime/src/config.py, ingest_api/runtime/src/ingestor.py
`convert_decimals_to_float` is expecting `dict` but we are passing type `Item`. Use ~`model_dump()`~  `to_dict()` to serialize Pydantic model to `dict`.
Also fixed `IngestorConstruct` lambda env variables pydantic validation in config `Settings()`.
=> fix: decimal to float serialization fix

stac_api/runtime/src/templates/stac-viewer.html
- This PR migrates Stamen Map references to use Stadia Maps (full migration notes [here](https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/))
- The migration is setup with my DevSeed email and to work with `*.delta-backend.com` domain
https://github.com/NASA-IMPACT/veda-backend/issues/291
- updates `stac-viewer.html` references from stamen maps to stadia maps
[- Page now shows map](https://dev.delta-backend.com/api/stac/index.html)
=> fix: migrate stamen map references to stadia maps

ingest_api/infrastructure/construct.py
- https://github.com/NASA-IMPACT/veda-backend/issues/308
- updated the role name to use `stack_name` since the original `stage` variable would default to `runner` across different stages causing deployments to `dev` to fail
- Locally deployed to dev successfully and confirmed that the previous resource `delta-backend-staging-stac-ingestion-api-runner` still exists and that `stac-ingestion-api-veda-backend-uah-dev-role` was created and the `dev` deployment succeeded
=> fix: update iam role name for stac ingestor to be unique across stages

.gitignore, README.md, local/Dockerfile.ingest, scripts/run-local-tests.sh
This PR makes it as simple as possible to run CI checks (linting and testing). It also includes conditional logging when those tests fail.
It also fixes the local ingestor container's build, which was overwriting the directory into which requirements were being installed
Closes #285
=> feat: local integration tests

.github/pull_request_template.md, stac_api/runtime/src/app.py, stac_api/runtime/src/templates/stac-viewer.html
https://github.com/NASA-IMPACT/veda-backend/issues/291
- Updated the endpoint value for the STAC viewer in order to properly render the collections on the webpage. 
- Added a PR template so that all new PRs will have a template for reference
- The endpoint is https://dev.openveda.cloud/collections which is incorrect which causes the collections filter to fail in the STAC viewer. 
https://github.com/NASA-IMPACT/veda-backend/assets/12633533/b272fb4c-23a9-41c2-8ce8-925c6760231a
- I didn't locally deploy or anything but here is [the working collections link](https://dev.openveda.cloud/api/stac/collections)
- I think we could technically also update https://github.com/NASA-IMPACT/veda-backend/blob/develop/stac_api/runtime/src/app.py#L79 to be:
```{"request": request, "endpoint": …
```
=> fix: update stac viewer endpoint value

raster_api/runtime/src/templates/stac-viewer.html
https://github.com/NASA-IMPACT/veda-backend/issues/291
- Update Stamen Maps to Stadia Maps 
- Addressed this changed in a [previous PR](https://github.com/NASA-IMPACT/veda-backend/pull/301) but didn't realize that I needed to update the raster api as well 
- Local testing on vscode without deploying to dev
=> fix: migrate stamen map references to stadia maps raster api

routes/infrastructure/construct.py
https://github.com/NASA-IMPACT/veda-data-airflow/pull/108 adds a cloudfront behavior that we don't want to maintain here. This is an attempt to avoid clobbering that deployment whenever our backend gets deployed.
=> fix(routes): make route behaviors additive

app.py, config.py, database/infrastructure/construct.py, ingest_api/infrastructure/config.py, ingest_api/infrastructure/construct.py, ingest_api/runtime/src/config.py
- Allows users to specify the subnet IDs to be used for the database
- Since we don't always get to create our own VPC, the subnets associated with it are not always one or the other type. We've had issues in the past with the private subnet type not being available in the VPC (`PRIVATE_ISOLATED`, `PRIVATE_EGRESS`, etc. This allows users to specify the subnet ids so we don't rely on a specific type.
- Deployed and manually checked that the database and the ingest lambdas were associated to the subnets provided
=> feat: configurable subnet ids

.github/workflows/develop.yml, .github/workflows/pr.yml, .github/workflows/tests/schemas/collection_schema.json, .github/workflows/tests/schemas/feature_schema.json, .github/workflows/tests/test_stac.py, ingest_api/runtime/requirements.txt
Currently, we test the api endpoints to ensure the correct response code (e.g. `200`).  This is a POC to use the open api validator to validate the response body against the stac open api spec.  Currently, the docs are showing the response for these two endpoints as just any string.  I've used a subset of the open api spec at https://api.stacspec.org/ to manually enter in a schema for now.
these tests can be run locally with the existing shell script: `./scripts/run-local-tests.sh`
=> chore: test api responses against openapi spec

ingest_api/infrastructure/construct.py
https://github.com/NASA-IMPACT/veda-backend/issues/328
Do not override the subnet configuration for the ingest api lambda.
Authenticated endpoints deployed to public subnets do not work using cloudfront
- Github PR action that runs cdk diff looks good
- Manually deployed to dev and confirmed that ingest api lambda in private subnets
- Confirmed AGW url and cloudfront url token and whoampi endpoints work
- Edited and reverted one collection
=> fix(api): do not override ingest api subnet config

database/infrastructure/construct.py
[Link to relevant GitHub issue](https://github.com/NASA-IMPACT/veda-architecture/issues/353)
- This is the original work https://github.com/NASA-IMPACT/veda-backend/pull/218/files which I'm making slight modifications of since the parameter storage_encrypted is not a part of [DatabaseInstanceFromSnapshot](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseInstanceFromSnapshot.html), but it is a valid parameter of [DatabaseInstance](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseInstance.html).
- In testing a test deployment that uses a snapshot, the deployment errors with:
```
Traceback (most recent call last):
File "/home/runner/work/veda-deploy/veda-deploy/veda-backend/app.py", line 66, in <module>
database = RdsConstruct(
File …
```
=> fix: update condition for setting storage_encrypted

.github/workflows/develop.yml, .github/workflows/main.yml, .github/workflows/pr.yml, CONTRIBUTING.md, ingest_api/runtime/requirements.txt, raster_api/runtime/setup.py
- python-multipart upgraded for security
- starlette version un-pinned (let fastapi manage this)
- all github actions upgraded to resolve node outdated node warnings
- conventional pr title linting action replaced with https://github.com/amannn/action-semantic-pull-request which can run on node > 16
- release tag generated before deployment in both develop and main workflows (makes it easier to re-run last deployment with configuration changes and should add the git release tag to the tags on aws resources)
Two dependabot alerts point back to the same python-multipart vulnerability, the second suggest upgrading starlette to version [0.36.2](https://github.com/encode/starlette/releases/tag/0.36.2) (the first release that pins python-multipart version at all). This PR instead requires …
=> fix: api dependencies upgrade

.github/workflows/develop.yml, .github/workflows/main.yml
This PR catches a few missed git action deprecated node warnings and removes an invalid input parameter from semantic release step.
=> ci: fix vcs release in deploy and upgrade action versions

.github/workflows/develop.yml, config.py
Force a trailing slash on the stac catalog url when building a stac-browser for a stac-api behind a cloudfront.
I temporarily updated the deploy action to push to the dev stack on push to this fix branch and confirmed that the browser at dev.openveda.cloud properly finds the stac api at dev.openveda.cloud/api/stac/.
=> fix: stac browser catalog url with cloudfront

.github/workflows/develop.yml, .github/workflows/main.yml, .github/workflows/pr.yml, database/runtime/handler.py, ingest_api/runtime/requirements.txt, ingest_api/runtime/requirements_dev.txt, ingest_api/runtime/src/vedaloader.py, ingest_api/runtime/tests/test_registration.py, setup.py
- Improve veda loader method that updates the summaries and extents of all items in a collection with a new `collection_temporal_extent_max` function that includes the maximum item `end_datetime` which is significantly different from an item's nominal `datetime` in collections of items that represent an entire year or range or dates.
- Removes ingest api large number test that is no longer needed because we no longer convert json values for the DDB schema.
- Pins fastapi at for ingest api tests (tech debt). Note that python-multipart is pinned at the new and secure version so it is still OK for us to use older versions of fastapi and starlette for now.
- Sets moto version to fix tests.
> **Note**
This requires incrementing `VEDA_DB_SCHEMA_VERSION` to cause the dashboard schema update to …
=> fix(db)!: update collection summaries on load items

scripts/run-local-tests.sh, setup.py
#348 
The run-local-tests.sh script runs the integration tests. This adds a run of the ingest api unit tests and generates a coverage report
- Instead of just manually documenting the existing tests, it would be beneficial to see what the current coverage level of those tests are and determine which areas should have more coverage.
Current baseline: 55% coverage
Output from running `./scripts/run-local-tests.sh`
```
==================================================================================== test session starts ====================================================================================
platform darwin -- Python 3.9.9, pytest-7.4.4, pluggy-1.4.0 -- /Users/stephenkilbourn/.pyenv/versions/3.9.9/bin/python
cachedir: .pytest_cache
rootdir: …
```
=> chore: run ingest tests with coverage in local test script

ingest_api/runtime/requirements.txt, ingest_api/runtime/requirements_dev.txt, ingest_api/runtime/src/main.py, ingest_api/runtime/src/monitoring.py
#289 
- Adds basic monitoring functionality to ingest API
- Deployed to temporary `otel` stack and viewed generated metrics and logs using POC Grafana instance
=> feat(otel): add otel to ingest API

config.py, stac_api/runtime/handler.py
Fix problem in which a stac-fastapi deployed behind a proxy (i.e. `customdomain.com`) with a custom root path (i.e. `/api/stac`)
- Fixed: API does not properly resolve `customdomain.com/api/stac` -> `customdomain.com/api/stac/`
- Fixed: API does not properly use custom root path in next links of paginated responses `customdomain.com/api/stac/...` links are returned as `customdomain.com/...` without the custom root path. 
The correction is to remove the gateway configuration from the Mangum ASGI handler for the stac-api handler.
- [Fastapi behind a proxy](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#proxy-with-a-stripped-path-prefix)
- [Mangum configuring an adaptar instance with api_gateway_base_path](https://mangum.io/adapter/#configuring-an-adapter-instance_) pattern that we …
=> fix(stac-api): next link and trailing slash bug in stac api url

ingest_api/runtime/src/auth.py, ingest_api/runtime/src/main.py
https://github.com/NASA-IMPACT/veda-data-airflow/issues/134
https://github.com/NASA-IMPACT/veda-backend/issues/347
- Update get_username to fall back on `sub` if `username` doesn't exist in token
- Added some more logging statements to make debugging easier in the future
- This fix is to enable a successful workflows API run since the workflow API passes a token to backend API and it's currently erroring
- Also, `sub` is a more definitive identifier because it represents a unique identifier compared to `username` 
- Relevant testing details
=> fix: update get_username function 

ingest_api/runtime/src/auth.py
Link to relevant GitHub issue
- Cast `sub` as `str` and remove default `None` since that will be cast as `str` which we want to avoid
```
>>> token = { }
>>> x = token.get("sub", None)
>>> str(x)
'None'
>>> exit()
```
- We were receiving this error when trying to kick off a `/dataset/publish/` workflow
`1 validation error for Ingestion\ncreated_by\n  str type expected (type=type_error.str)` and, to be safe, we are casting `sub` as `str`
- Locally deployed on dev and ran `/dataset/publish/` successfully https://4e76fa52-1de6-41a5-b364-691fb1cc69f4.c18.us-west-2.airflow.amazonaws.com/dags/veda_ingest_raster/graph?run_id=0767fd24-461d-481f-85eb-2ebb4662d144_617296f2-18e1-4711-9961-8a542bb8958b_0&execution_date=2024-05-02+19%3A54%3A13.422305%2B00%3A00
=> fix: cast sub as str

ingest_api/infrastructure/config.py, ingest_api/runtime/src/config.py
- Allow ingest-api to be deployed without a custom root path by setting the default config for fastapi root path parameter to None.
- When the ingest API is deployed to a stack without a cloud front and custom host it should not apply an additional root path.
Deployed to a test branch using a custom subdomain instead of a cloudfront with custom root path.
=> fix(ingest): default empty string for root path in ingest api construct

app.py, ingest_api/runtime/handler.py, ingest_api/runtime/src/main.py, ingest_api/runtime/src/monitoring.py, raster_api/infrastructure/construct.py, raster_api/runtime/src/config.py, raster_api/runtime/src/monitoring.py, stac_api/infrastructure/construct.py, stac_api/runtime/src/app.py, stac_api/runtime/src/config.py, stac_api/runtime/src/monitoring.py
Changes to observability in backend APIs:
- Include monitoring for STAC API endpoints
- service dimension change for ingest api (incorrectly had "raster-api"), add monitoring to ingest handler
- include path params and post body in logs
- include stage dimension in metrics to distinguish between instances (i.e. dev, staging, etc.)
- include metrics for each api path (i.e. collections/, collections/{collection_id}, mosaic/register, etc.
- deployed to `monitor` veda-backend stack and created tables in Grafana. See[ ticket](https://github.com/NASA-IMPACT/veda-backend/issues/349) for details. 
- Confirmed logs and metrics are being sent for raster, stac and ingest APIs
=> fix: backend monitoring changes

routes/infrastructure/construct.py
[Link to relevant GitHub issue](https://github.com/NASA-IMPACT/veda-architecture/issues/431)
- Enable logging on the cloudfront distribution. Setting `enable_logging` to true will create an S3 bucket to write logs to with the necessary permissions for cloudfront to successfully send logs. 
- Best practices
- Deployed to UAH dev and MCP test
=> feat: enable cloudfront logging

ingest_api/runtime/src/config.py
Make `cognito_domain` optional in ingestor lambda.
=> fix: optional cognito domain in ingestor lambda

ingest_api/infrastructure/config.py, ingest_api/infrastructure/construct.py
Data access role arn is optional in raster API, but ingestor makes it required, which doesn't make sense.
- Made raster_data_access_role_arn env var optional
- Shouldn't be required
- Relevant testing details
=> fix: make data access role optional in ingestor

ingest_api/infrastructure/config.py, ingest_api/infrastructure/construct.py, ingest_api/runtime/src/auth.py, ingest_api/runtime/src/config.py, ingest_api/runtime/src/validators.py
https://github.com/NASA-IMPACT/veda-data/issues/134
- Add optional requester pays configuration to ingest API to validate accessibility of assets in buckets that require requester pays _if_ the titiler been configured to use requester pays
- Ingest API verifies that all hrefs in new items are accessible to the titiler but is failing in cases where the bucket requires requester pays configuration
I deployed this manually to dev and confirmed that the change resolves the unable to access objects errors when configured to use requester pays.
=> fix(ingest): requester pays config in validation

raster_api/runtime/setup.py
Added latest version of rio-tiler (recorded as stable [here](https://github.com/US-GHG-Center/ghgc-backend/issues/72) ) 
in raster API.
- Added version `6.5.0` of `rio-tiler` in raster API
GHGC is preparing to deploy all VEDA dependencies through a common repository [`veda-deploy`](https://github.com/NASA-IMPACT/veda-deploy). Some of the forked repos in GHGC were ahead of VEDA and to reflect those changes, the version of `rio-tiler` is being upgraded.
=> chore: Add rio-tiler version in raster API 

ingest_api/runtime/src/schemas.py
The web-map-links stac extension that we use for arcgis collections to host WMS URLs contains optional fields in the collection link ("wms:layers", "wms:styles"). Currently, when we ingest a collection, these fields are removed.
- Allows adding extra fields to the collection links.
- see issue ☝️ 
- Publish a collection with extra fields, it should show up in the catalog
=> fix: allow extra fields in collection links to support extensions

ingest_api/infrastructure/config.py, ingest_api/infrastructure/construct.py
When an external assume role hasn't been provided, the ingestor doesn't have access to any s3 bucket/keys causing all the `/ingestions` requests to fail because of the "Asset not accessible" validation error.
This PR fixes this by using the same bucket/key configuration (can also be passed via `VEDA_BUCKETS` and `VEDA_KEY` env var) that the raster API uses.
- The ingestor should have the same s3 permissions as the raster API to validate if an asset is accessible from the raster api.
=> fix: ingestor role to have s3 access

ingest_api/runtime/requirements.txt
- xarray, xstac, and zarr requirements removed from ingest-api
github search found no import of xarray, xstac, or zarr
=> chore(ingest): remove unused xarray, xstac, and zarr requirements

.github/workflows/tests/test_stac.py
#384 
This updates the existing integration tests to cover each of the stac endpoints listed in the docs
this will run with the existing script: `./scripts/run-local-tests.sh`
=> chore: Improve stac integration tests

stac_api/runtime/src/links.py, stac_api/runtime/src/render.py
Render fix for titiler-pgstac v1 upgrade
=> fix: render fix for titiler-pgstac v1 upgrade

.gitignore
Add `.idea` to `.gitignore`
Some people (me) use Jetbrains IDE's and not VS Code
I've not commited up the `.idea` folder because I can't now :smile:
=> chore: add gitignore entry for Jetbrains IDEs

.github/workflows/develop.yml, .github/workflows/main.yml
Adds auth requirements installation before ingest API tests to address the error in the workflow https://github.com/NASA-IMPACT/veda-backend/actions/runs/10268965811
For later: We should reuse tests rather than duplicate them in each workflow
=> fix: add auth requirements install for ingest-api tests

.github/actions/cdk-deploy/action.yml, ingest_api/infrastructure/construct.py, raster_api/infrastructure/construct.py, s3_website/infrastructure/construct.py, stac_api/infrastructure/construct.py
Towards #402 
This PR ensures that outputs from CDK for the following services: `stac-api`, `ingest-api`, `raster-api` and `stac-browser` are available and deterministically named.
Prior to this change, if you piped the outputs to a file, you get a combination of `export_name` and a hash, which will cause issues when trying to retrieve values from the outputs for later jobs.
To get around this, I've specified the `key` parameter which explicitly tells CDK to save the outputs under a name without any logical ID logic from CDK.
I've also renamed the outputs file for this action to be `veda-backend-cdk-outputs.json` just so it's clear which stack it's for and prevents any clashes from further stacks we deploy.
You can run a `cdk deploy/diff` locally and notice that the outputs are generated …
=> feat: deterministic outputs of service urls

ingest_api/runtime/requirements.txt, ingest_api/runtime/tests/conftest.py
This PR bumps up `fastapi` in `ingest_api` to address: https://github.com/NASA-IMPACT/veda-backend/security/dependabot/4
The tests failed and it appears to be: https://github.com/fastapi/fastapi/discussions/11102 where root path behaviour changed in some uvicorn update
So I set it to `""` rather than `"/"` and this appears to work 🤷
=> fix: address dependabot alert 4

s3_website/infrastructure/construct.py
https://github.com/NASA-IMPACT/veda-routes/issues/2
Changing the output of the STAC Browser from hostname to bucket name
You can't import a bucket into a stack by hostname alone, could infer it with some regex, but seems safer to just export the name. You can then get the hostname from the imported construct
Run locally and the exported value indeed changed
=> fix: output stac bucket name not host

routes/infrastructure/config.py, routes/infrastructure/construct.py
- Change supports multiple alternate domain names (CNAMES) for cloudfront distribution for production since it also needs an alternate domain name of `openveda.cloud`
- So that we don't have to manually configure this and to empower those without MCP access to successfully deploy mcp-prod
- Tested in UAH account on new stack `veda-jt-test`
=> fix: update domain names to support multiple domain names for prod

setup.py
We were seeing `cannot import name 'mock_dynamodb' from 'moto` because moto made a breaking change on the imports in moto version 5. 
We already have `moto[dynamodb, ssm]>=4.0.9,<5.0` in the ingest api `requirements_dev` to address this, but there was an unpinned version in the `setup.py`.  I'm making this change to just have the import with the pinned version in a single location.
=> chore: remove moto from setup. leave in requirements_dev

stac_api/runtime/tests/conftest.py, stac_api/runtime/tests/test_transactions.py
Link to relevant GitHub issue
- Description of the changes made
- Description of why the changes were made
- Relevant testing details
=> fix: fix transaction unit test

.github/workflows/pr.yml, scripts/run-local-tests.sh, stac_api/runtime/src/validation.py, stac_api/runtime/tests/conftest.py, stac_api/runtime/tests/test_transactions.py
I've added a small change in the `stac_api/runtime/tests/conftest.py`. This gives a similar error on each of the attempts to POST: The error error:
```
>       response = self.api_client.post(
collections_endpoint, json=self.invalid_stac_collection
)
E       AttributeError: 'async_generator' object has no attribute 'post'
stac_api/runtime/tests/test_transactions.py:63: AttributeError
```
this got past the starlette error that we were seeing in develop:
```
self = <starlette.datastructures.State object at 0x10bf0b1f0>, key = 'get_connection'
def __getattr__(self, key: typing.Any) -> typing.Any:
try:
return self._state[key]
except KeyError:
message = "'{}' object has no attribute '{}'"
>           raise AttributeError(message.format(self.__class__.__name__, key))
E           AttributeError: …
```
=> test: Fix transaction unit tests

ingest_api/runtime/src/schema_helpers.py
Fix temporal validator in cases where a collection has a `null` enddate as per STAC spec: https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#temporal-extent-object
Tested with the following dataset config:
```json
{
"collection": "fldas-soil-moisture-anomalies",
"title": "FLDAS Surface Soil Moisture Anomalies",
"data_type": "cog",
"spatial_extent": {
"xmin": -180,
"ymin": -60,
"xmax": 180,
"ymax": 90
},
"temporal_extent": {
"startdate": "1982-01-01T00:00:00Z",
"enddate": null
},
"license": "not-provided",
"description": "A 10 km global data product with 40 years of monthly soil moisture anomalies for food and water security monitoring from the Famine Early Warning System Network (FEWS NET) Land Data Assimilation System",
"is_periodic": false, …
```
=> fix: check none enddate in temporal validator

.github/workflows/cicd.yml
Trying to get cicd action running on push to develop branch
=> fix: typo in define-environment

network/infrastructure/construct.py, standalone_base_infrastructure/network_construct.py
Add ECR endpoint to VPC to allow pulling images.
=> feat: add ecr endpoint

ingest_api/runtime/Dockerfile, raster_api/runtime/Dockerfile, stac_api/runtime/Dockerfile
Fixes issues with new 3.11 runtimes (already deployed to dev).
Also adds a failure condition to the raster API Dockerfile (which will fail if there is an issue with the lambda runtime).
=> fix: 3.11 runtime adjustments

ingest_api/runtime/src/validators.py
Resolve new `AttributeError: 'AnyHttpUrl' object has no attribute 'strip'"` error from ingest-api collection exists validator
=> fix: cast stac url as string in collection exists validator

ingest_api/runtime/src/schemas.py, ingest_api/runtime/src/services.py
Fix the dynamo table write method to use the correct ingestion schema method name:
```
def write(self, ingestion: schemas.Ingestion):
self.table.put_item(Item=ingestion.dynamodb_dict())
```
=> fix: change dynamo db method reference

raster_api/runtime/src/app.py
https://github.com/NASA-IMPACT/veda-backend/issues/458
- Our colormaps endpoint doesn't include the custom colormaps
- https://jtran.delta-backend.com/api/raster/docs#/ColorMaps/getColorMaps
You will see the endpoint now returns the custom colormaps at the end of the list
```
{
"colorMaps": [
"accent",
.
.
.
"epa-ghgi-ch4",
"nlcd",
"soil_texture",
"surface_temperature",
"tornado_ef_scale"
],
"links": [
{
"href": "https://delta-backend.com/api/raster/colorMaps",
"rel": "self",
"type": "application/json",
"title": "List of available colormaps"
},
{
"href": "https://delta-backend.com/api/raster/colorMaps/{colorMapId}",
"rel": "data",
"type": "application/json",
"templated": true,
"title": "Retrieve colorMap metadata"
},
{
"href": "https://delta-backend.com/api/raster/colorMaps/{colorMapId}?fo …
```
=> fix(raster-api): update colormaps to include additional custom colormaps

raster_api/runtime/src/app.py
https://github.com/NASA-IMPACT/veda-backend/issues/458#issuecomment-2707630918
- `colorMaps` endpoint was returning the new colormaps but `colorMaps/colorMapId` wasn't. 
https://jtran.delta-backend.com/api/raster/docs#/ColorMaps/getColorMap
=> fix: set supported_colormaps for colormapfactory

ingest_api/runtime/src/collection_publisher.py, ingest_api/runtime/src/schemas.py
Add default for assets in ingest api collection validation so it's not a required field in pydantic  v2 as per the migration guide:
https://docs.pydantic.dev/dev/migration/#required-optional-and-nullable-fields
=> fix: add default for collection assets

stac_api/runtime/src/app.py, stac_api/runtime/src/config.py
https://github.com/NASA-IMPACT/veda-backend/issues/473
- Pagination was not working due changes made to [Pagination extension ](https://stac-utils.github.io/stac-fastapi/migrations/v3.0.0/#request-models). Updating to use a request model fixed it.
https://jtran.delta-backend.com/api/stac/collections/snow-projections-diff-245/items?token=next:snow-projections-diff-245:CSCD_SWE_tavg_ssp245_20770401_percChange.cog
=> fix: pagination in stac api

stac_api/infrastructure/construct.py
Link to relevant GitHub issue
- Updated to conditionally add certain env vars based on setting of `stac_enable_transactions`
- https://github.com/NASA-IMPACT/veda-deploy/actions/runs/14582901475/job/40903966433 Getting an error trying to deploy MCP test which I believe is due to a null env var value:
```
jsii.errors.JavaScriptError: 
@jsii/kernel.SerializationError: Passed to parameter props of new aws-cdk-lib.aws_lambda.Function: Unable to deserialize value as aws-cdk-lib.aws_lambda.FunctionProps
├── 🛑 Failing value is an object
│      { '$jsii.struct': [Object] }
╰── 🔍 Failure reason(s):
╰─ Key 'environment': Unable to deserialize value as map<string> | undefined
├── 🛑 Failing value is an object
│      { '$jsii.map': [Object] }
╰── 🔍 Failure reason(s):
╰─ Key 'VEDA_STAC_CLIENT_ID': …
```
=> fix: add debugging to stac api lambda envs

app.py, ingest_api/infrastructure/construct.py, raster_api/infrastructure/construct.py, stac_api/infrastructure/construct.py
- remove `allow_public_subnet` from stac and raster api since they use private subnets
- remove unused `db_vpc_subnets` paramater in ingest api
- remove `allow_public_subnet` from `IngestorConstruct` lambda since it should be placed in private subnet and needs internet access for keycloak auth
- This branch was deployed to test.openveda.cloud and [ida-ndwi-difference-test-ingest-api-keycloak](https://dev.openveda.cloud/stac/collections/ida-ndwi-difference-test-ingest-api-keycloak) was ingested using the ingest API directly
=> fix: remove allow public subnets from lambdas

ingest_api/runtime/src/schemas.py
For a field to be [optional in pydantic v2 ](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields)it must be set to None or else it will still be required. 
This PR sets `item_assets` and `links` as optional. 
- manually deployed and tested in dev.openveda.cloud/api/ingest
=> fix: make item assets optional

.github/actions/cdk-deploy/action.yml, .github/workflows/tests/conftest.py, .github/workflows/tests/test_raster.py, config.py, raster_api/infrastructure/config.py, raster_api/runtime/setup.py, raster_api/runtime/src/app.py, raster_api/runtime/src/extensions.py, stac_api/infrastructure/config.py, stac_api/infrastructure/construct.py
#482 
- Updates raster API runtime to 3.12
- Updates titiler and titiler-pgstac
- Updates tests to use new endpoints for breaking changes to point queries and TMS inputs
- Flag to disable tests in CI (In veda-deploy, we perform integration tests against deployed services as a separate step after deployment. Disabling the pre-deploy tests makes those deployments faster. Default CI behaviour is unchanged.)
~- [ ] TODO some endpoints no longer have debug headers, I would like to re-enable these before merging, but this is fairly low priority~ see comments
- Pending some fixes to our SIT environment, this has been deployed to https://ig3cl55i3b.execute-api.us-west-2.amazonaws.com/docs
- Integration+unit tests pass
- Local manual tests pass/seem fine
- In particular, I reproduced the issue …
=> fix(dependencies): titiler and rio-tiler upgrade

stac_api/runtime/setup.py
https://github.com/stac-utils/stac-fastapi-pgstac/issues/262
https://github.com/NASA-IMPACT/veda-architecture/issues/632
- Upgrade stac-fastapi.pgstac to root_path fix version to resolve duplicated root path in self and next links.
- Deployed to test instance and confirmed that dynamic urls do not contain duplicated paths.
=> fix(stac): resolve duplicated root path bug

stac_api/runtime/src/render.py
#474 
removes the json_dumps parameter from the ConfigDict in model_config
it is no longer supported by Pydantic V2
Relevant testing details
=> fix: use replace deprecated custom json serialization with default pydantic v2 model_config

ingest_api/runtime/src/services.py, ingest_api/runtime/tests/conftest.py, scripts/run-local-tests.sh
This resolves the deprecation warning in #510 
```
PydanticDeprecatedSince20: The `parse_obj` method is deprecated; use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
```
Swapped the  The `parse_obj` method with `model_validate` instead.
=> fix: update parse_obj to model_validate
